{% set name = "presidio-anonymizer" %}
{% set version = "2.2.355" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/microsoft/presidio/archive/refs/tags/{{ version }}.tar.gz
  sha256: fc0b6b8ff84da03c79702310e7af060116074ce1a39f6c29433e348eee76707b

build:
  noarch: python
  script: cd {{ name }} && {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - poetry-core
  run:
    - python >={{ python_min }},<4
    - pycryptodome >=3.10.1
    - azure-core
  run_constrained:
    - flask >=1.1

test:
  imports:
    - presidio_anonymizer
  requires:
    - python {{ python_min }}
    - pip
  commands:
    - pip list
    - pip check

about:
  home: https://github.com/microsoft/presidio
  summary: 'Presidio Anonymizer package - replaces analyzed text with desired values.'
  description: |
    Presidio Anonymizer package - replaces analyzed text with desired values.
  license: MIT
  license_file: LICENSE
  doc_url: https://microsoft.github.io/presidio
  dev_url: https://github.com/microsoft/presidio

extra:
  recipe-maintainers:
    - julcsii
    - geoHeil
    - heckert
