{% set name = "presidio-anonymizer" %}
{% set version = "2.2.356" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/microsoft/presidio/archive/refs/tags/{{ version }}.tar.gz
  sha256: be7fe65784d06f46471d92b1f1c471c7ce88dd64550554f7722087921c8635f6

build:
  noarch: python
  script: cd {{ name }} && {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - poetry-core
  run:
    - python >={{ python_min }},<4
    - pycryptodome >=3.10.1
    - azure-core
  run_constrained:
    - flask >=1.1
    - gunicorn

test:
  imports:
    - presidio_anonymizer
  requires:
    - python {{ python_min }}
    - pip
  commands:
    - pip list
    - pip check

about:
  home: https://github.com/microsoft/presidio
  summary: 'Presidio Anonymizer package - replaces analyzed text with desired values.'
  description: |
    Presidio Anonymizer package - replaces analyzed text with desired values.
  license: MIT
  license_file: LICENSE
  doc_url: https://microsoft.github.io/presidio
  dev_url: https://github.com/microsoft/presidio

extra:
  recipe-maintainers:
    - julcsii
    - geoHeil
    - heckert
